# Generated by Django 5.1.6 on 2025-03-01 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('driver_name', models.CharField(max_length=255)),
                ('truck_number', models.IntegerField()),
                ('current_lat', models.FloatField()),
                ('current_lng', models.FloatField()),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CycleHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.IntegerField()),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('start_lat', models.FloatField()),
                ('start_lng', models.FloatField()),
                ('end_lat', models.FloatField()),
                ('end_lng', models.FloatField()),
                ('distance', models.FloatField()),
                ('annotations', models.TextField(blank=True, null=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_hours', to='api.log')),
            ],
        ),
    ]
